In [11]:
# No warnings
import warnings
warnings.filterwarnings('ignore') # Filter out warnings

# data analysis and wrangling
import pandas as pd
import numpy as np
import random as rnd

pd.set_option('display.max_columns', 100) # Print 100 Pandas columns

# visualization
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

# machine learning
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB # Gaussian Naive Bays
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier #stochastic gradient descent
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split


import tensorflow as tf
from datetime import datetime
import os
import pathlib

df = pd.read_csv('Hainan_RawBiogas_Categorical.csv')
df.head()

,Year,Pig Manure (t),Cassava (t),Fish waste water (t),Kitchen food waste (t),Municipal fecal residue (t),Tea waste (t),Chicken litter (t),Bagasse feed (t),Alcohol waste (t),Chinese medicine waste (t),Energy grass (t),Banana fruit shafts (t),Lemon waste (t),Percolate (t),Other waste (t),Raw Biogas Produced (m3)
0,2014,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5154.0
1,2014,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3426.0
2,2014,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5885.0
3,2014,14.9,0.0,0.0,0.0,0.0,0,0.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3727.0
4,2014,0.0,0.0,0.0,0.0,0.0,0,0.0,16.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4072.0

In [12]:
X = df.drop("Raw Biogas Produced (m3)", axis=1) # Training & Validation data
Y = df["Raw Biogas Produced (m3)"] # Response / Target Variable

X_train=df

In [ ]:
#from sklearn.ensemble import RandomForestClassifier

rfc= RandomForestClassifier()

rfc.fit(X_train,Y_train)

Y_pred_train = rfc.predict(X_train)
mean_sqrt_error_train = np.sqrt(np.mean((Y_pred_train-Y_train)**2))
print('RFC Training error: \n', mean_sqrt_error_train)

Y_pred_val = rfc.predict(X_val)
mean_sqrt_error_val = np.sqrt(np.mean((Y_pred_val-Y_val)**2))
print('RFC Test error: \n', mean_sqrt_error_val)

training_accu= rfc.score(X_train, Y_train)
test_accu= rfc.score(X_val, Y_val)

print('RFC Training Accuracy: \n', training_accu)
print('RFC Test Accuracy: \n', test_accu)