In [166]:
# import_notebooks is a custom python script
# this line makes it possible to import functions from other IPython notebooks
from import_notebooks import *

In [167]:
# Here we import all the functions (*) from these notebooks
from Hainan_Data_Cleaning import *
from time_shift_dataframe import *
from Stratified_Split import *
from Cumulative import *
from Rollingsum import *
from LR_model import *
from Classification_Functions import *
from nn_model_keras import *

from Utilities import *

Biogas fermentation is a series of processes where microorganisms break down biodegradable materials (usually in the absence of oxygen), thus it is often attributed as anaerobic digestion. The break-down of these biodegradable materials (such as biomass) will produce simpler molecules, where some of these products are in the form of bio-gas. The detailed mechanism of how biogas fermentation occurs depends on the microorganisms involved, as well as types of feedstock (biomass) used and operating conditions (temperature, pH, etc). In general, we can describe the mechanism into four key biological and chemical stages: hydrolysis, acidogenesis, acetogenesis, methanogenesis

# We are seperating the inputs into 4 categories: Carbohydrate, Protein, Lipid and Others

Carbohydrate:
Cassava
Tea Waste
Bagasse
Chinese Medicine Waste
EnergyGrass
Banana Fruit Shafts
Lemon Waste

Protein:
MunicipalFecalWaste
PigManure
ChickenWaste
FishWastewater

Lipid:
Kitchen Food Waste

Others:
AlcoholWaste
Percolate
Other
NaOH
FeCl
PAM
Defoamer

In [177]:
# load_hainan_data() is from Hainan_Data_Cleaning and it loads hainan data
df = load_hainan_data()
df_ts = timeshift_df(df, 21)

df_ts.columns.values
df_ts_relfeatures = df_ts.drop(['Year', 'Month', 'Day','BioCNG', 'LiquidFertilizer',
       'SolidFertilizer', 'WasteWater', 'SolidResidues','ProjectElectricity',
       'OfficeElectricity', 'Water', 'Diesel'], axis=1)

print(df_ts_relfeatures.shape[0])
df_ts_relfeatures = df_ts_relfeatures.apply(pd.to_numeric, errors='coerce')
df_ts_relfeatures = df_ts_relfeatures.dropna()
print(df_ts_relfeatures.shape[0])

df_ts_relfeatures_roll = rollingsum(df_ts_relfeatures,35)

1407
1407

In [178]:
df = df_ts_relfeatures
df.head()

,RawBiogas,PigManure,Cassava,FishWastewater,KitchenFoodWaste,MunicipalFecalWaste,TeaWaste,ChickenWaste,Bagasse,AlcoholWaste,ChineseMedicineWaste,EnergyGrass,BananaFruitShafts,LemonWaste,Percolate,Other,NaOH,FeCl2,PAM,Defoamer
0,6839.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,6251.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,7593.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,6732.0,14.9,0.0,0.0,0.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,7916.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [179]:
df_final = df_ts_relfeatures_roll
print(df_final.shape)
df_final.head()

(1372, 20)

,RawBiogas,PigManure,Cassava,FishWastewater,KitchenFoodWaste,MunicipalFecalWaste,TeaWaste,ChickenWaste,Bagasse,AlcoholWaste,ChineseMedicineWaste,EnergyGrass,BananaFruitShafts,LemonWaste,Percolate,Other,NaOH,FeCl2,PAM,Defoamer
0,150021.0,7020.91,0.0,0.0,0.0,0.0,0.0,0.0,272.07,0.0,0.0,0.0,0.0,0.0,0.0,267.78,5184.8,0.0,0.0,0.0
1,147944.0,7023.89,0.0,0.0,0.0,0.0,0.0,0.0,285.07,0.0,0.0,0.0,0.0,0.0,0.0,267.78,5184.8,0.0,0.0,0.0
2,141693.0,7029.93,0.0,0.0,0.0,0.0,0.0,0.0,291.07,0.0,0.0,0.0,0.0,0.0,0.0,267.78,5184.8,0.0,0.0,0.0
3,138845.0,7045.29,0.0,0.0,0.0,0.0,0.0,0.0,300.07,0.0,0.0,0.0,0.0,0.0,0.0,267.78,5184.8,0.0,0.0,0.0
4,132113.0,7036.69,0.0,0.0,0.0,0.0,0.0,0.0,302.07,0.0,0.0,0.0,0.0,0.0,0.0,267.78,5184.8,0.0,0.0,0.0

In [180]:
df_final['Carbohydrate']=df_final['Cassava']+df_final['TeaWaste']+df_final['Bagasse']+df_final['ChineseMedicineWaste']+df_final['EnergyGrass']+df_final['BananaFruitShafts']+df_final['LemonWaste']
df_final['Protein']=df_final['MunicipalFecalWaste']+df_final['PigManure']+df_final['ChickenWaste']+df_final['FishWastewater']
df_final['Lipid']=df_final['KitchenFoodWaste']
df_final['Others']=df_final['AlcoholWaste']+df_final['Percolate']+df_final['Other']+df_final['NaOH']+df_final['FeCl2']+df_final['PAM']+df_final['Defoamer']

In [181]:
df_final= df_final.drop(['PigManure', 'Cassava', 'FishWastewater','KitchenFoodWaste', 'KitchenFoodWaste',
       'MunicipalFecalWaste', 'TeaWaste', 'ChickenWaste','Bagasse',
       'AlcoholWaste', 'ChineseMedicineWaste', 'EnergyGrass','BananaFruitShafts','LemonWaste','Percolate','Other','NaOH','FeCl2','PAM','Defoamer'], axis=1)

In [182]:
x_train_r, y_train_r, x_test_r, y_test_r = test_train_for_regression(df_final)
x_train_c, y_train_c, x_test_c, y_test_c = test_train_for_classification(df_final, num_buckets = 7)
x_train_c_1, y_train_c_1, x_test_c_1, y_test_c_1 = test_train_for_classification(df_final, \
                                output_var="RawBiogas", \
                                num_buckets = 7, one_hot=True)

print(x_train_r.shape,  y_train_r.shape, x_test_r.shape, y_test_r.shape)
# print(x_train_r.columns.values)
df_final

(1097, 4) (1097,) (275, 4) (275,)

      RawBiogas  Carbohydrate  Protein    Lipid   Others
0      150021.0        272.07  7020.91     0.00  5452.58
1      147944.0        285.07  7023.89     0.00  5452.58
2      141693.0        291.07  7029.93     0.00  5452.58
3      138845.0        300.07  7045.29     0.00  5452.58
4      132113.0        302.07  7036.69     0.00  5452.58
5      127411.0        301.07  7043.69     0.00  5452.58
6      125965.0        289.57  7033.54     0.00  5452.58
7      124429.0        286.57  7026.16     0.00  5452.58
8      122235.0        304.07  7012.16     0.00  5452.58
9      118948.0        317.07  7004.18     0.00  5452.58
10     113166.0        319.57  6996.70     0.00  5452.58
11     108905.0        324.57  6986.68     0.00  5452.58
12     103302.0        344.57  6992.36     0.00  5452.58
13      98087.0        364.57  6998.52     0.00  5452.58
14      92803.0        384.57  7004.92     0.00  5452.58
15      89493.0        404.57  7012.10     0.00  5452.58
16      86677.0        434.57  7020.68     0.00  5452.58
17      83450.0        462.57  7026.84     0.00  5452.58
18      80869.0        494.57  7032.36     0.00  5452.58
19      78041.0        524.57  7037.62     0.00  5452.58
20      77017.0        554.57  7047.14     0.00  5452.58
21      74465.0        575.57  7053.76     0.00  5452.58
22      71486.0        575.50  7057.04     0.00  5452.58
23      72830.0        579.75  7044.10     0.00  5452.58
24      72861.0        594.75  7038.34     0.00  5424.68
25      73428.0        609.75  7032.20     0.00  2985.52
26      76801.0        614.75  7022.64     0.00  1636.67
27      81735.0        626.75  7015.95     0.00  1248.60
28      82248.0        635.75  7009.39     0.00   136.72
29      82557.0        636.75   195.59     0.00   108.42
...         ...           ...      ...      ...      ...
1342   669647.0        591.25  6263.25  3091.33  9347.10
1343   666654.0        618.08  6245.43  3077.21  8945.10
1344   662931.0        644.99  6309.29  3083.45  8554.10
1345   663282.0        677.02  6318.33  3106.55  8336.10
1346   661399.0        712.19  6360.63  3092.82  8190.10
1347   660361.0        739.84  6378.88  3123.90  8314.00
1348   659580.0        766.95  6441.43  3117.01  8194.00
1349   659877.0        789.58  6461.44  3087.97  8255.00
1350   664755.0        822.61  6474.50  3119.04  8379.00
1351   670228.0        860.84  6456.77  3133.62  8436.00
1352   677058.0        906.79  6530.97  3117.38  8447.00
1353   682037.0        957.15  6535.89  3144.52  8378.00
1354   685067.0        964.15  6554.51  3160.80  8392.00
1355   685764.0        957.93  6562.31  3109.34  8375.00
1356   684019.0        956.67  6584.37  3117.34  8538.00
1357   686196.0        976.30  6555.05  3109.06  8533.00
1358   687660.0        976.28  6548.01  3102.12  8546.00
1359   689828.0        971.46  6557.43  3162.64  8564.00
1360   684431.0        965.27  6575.91  3162.90  8574.00
1361   674541.0        966.93  6612.41  3127.44  8321.00
1362   666031.0        957.37  6606.27  3155.68  8231.00
1363   653582.0        950.55  6609.85  3150.02  8187.00
1364   643643.0        936.38  6602.35  3161.58  8354.00
1365   631296.0        916.01  6588.11  3202.64  8578.00
1366   625896.0        915.28  6556.09  3226.82  8720.00
1367   615745.0        877.35  6510.27  3216.54  8837.00
1368   612625.0        868.80  6452.85  3187.38  9062.00
1369   610536.0        868.80  6513.05  3174.29  9276.00
1370   610197.0        839.09  6518.71  3191.11  9623.00
1371   609714.0        812.54  6515.87  3216.43  9798.00

[1372 rows x 5 columns]

In [183]:
# Linear Regression
lr = run_lm(x_train_r, y_train_r, x_test_r, y_test_r)

Starting linear regression model.
                            OLS Regression Results
==============================================================================
Dep. Variable:              RawBiogas   R-squared:                       0.778
Model:                            OLS   Adj. R-squared:                  0.777
Method:                 Least Squares   F-statistic:                     956.2
Date:                Mon, 16 Apr 2018   Prob (F-statistic):               0.00
Time:                        13:39:20   Log-Likelihood:                -14074.
No. Observations:                1097   AIC:                         2.816e+04
Df Residuals:                    1092   BIC:                         2.818e+04
Df Model:                           4
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const         1.383e+05   5789.326     23.890      0.000    1.27e+05     1.5e+05
Carbohydrate   104.2475      4.150     25.121      0.000      96.105     112.390
Protein          2.7718      2.596      1.068      0.286      -2.322       7.866
Lipid          183.9770      6.626     27.764      0.000     170.975     196.979
Others           0.3448      0.283      1.218      0.224      -0.211       0.900
==============================================================================
Omnibus:                       43.849   Durbin-Watson:                   2.094
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               48.221
Skew:                           0.507   Prob(JB):                     3.38e-11
Kurtosis:                       2.834   Cond. No.                     2.73e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.73e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
The mean absolute error of linear regression on training set is:  71885.5362553
The mean absolute error of linear regression test set is:  74125.2913808

In [184]:
rr = run_ridge(x_train_r, y_train_r, x_test_r, y_test_r, alpha = 0.5)

# Classification
lm = LogisticModel(x_train_c, y_train_c, x_test_c, y_test_c)

dt = DecisionTree(x_train_c, y_train_c, x_test_c, y_test_c)

rf = RandomForest(x_train_c, y_train_c, x_test_c, y_test_c)

nb = NaiveBayes(x_train_c, y_train_c, x_test_c, y_test_c)


# Neural Net 
l_and_m = run_keras_nn(x_train_c_1, y_train_c_1, x_test_c_1, y_test_c_1, \
             epochs=10, hidden_layers=6, layer_neurons = 300, \
             activation='tanh', learning_rate=0.01)

The mean absolute error of ridge regression on training set is:  86617.8174403
The mean absolute error of ridge regression test set is:  89217.5001516
Starting keras model.
4
7
Epoch 1/10
1097/1097 [==============================] - 3s 3ms/step - loss: 1.7278 - mean_absolute_error: 0.2174 - categorical_accuracy: 0.3273
Epoch 2/10
1097/1097 [==============================] - 1s 748us/step - loss: 1.6993 - mean_absolute_error: 0.2117 - categorical_accuracy: 0.3573
Epoch 3/10
1097/1097 [==============================] - 1s 651us/step - loss: 1.7262 - mean_absolute_error: 0.2137 - categorical_accuracy: 0.3400
Epoch 4/10
1097/1097 [==============================] - 1s 742us/step - loss: 1.5647 - mean_absolute_error: 0.2061 - categorical_accuracy: 0.3993
Epoch 5/10
1097/1097 [==============================] - 1s 692us/step - loss: 1.8467 - mean_absolute_error: 0.2233 - categorical_accuracy: 0.2644
Epoch 6/10
1097/1097 [==============================] - 1s 747us/step - loss: 1.6159 - mean_absolute_error: 0.2118 - categorical_accuracy: 0.3473
Epoch 7/10
1097/1097 [==============================] - 1s 701us/step - loss: 1.6396 - mean_absolute_error: 0.2115 - categorical_accuracy: 0.3601
Epoch 8/10
1097/1097 [==============================] - 1s 628us/step - loss: 1.5458 - mean_absolute_error: 0.2053 - categorical_accuracy: 0.3929
Epoch 9/10
1097/1097 [==============================] - 1s 642us/step - loss: 1.5921 - mean_absolute_error: 0.2077 - categorical_accuracy: 0.3418
Epoch 10/10
1097/1097 [==============================] - 1s 617us/step - loss: 1.5942 - mean_absolute_error: 0.2105 - categorical_accuracy: 0.3646
275/275 [==============================] - 1s 2ms/step
[1.7408255598761819, 0.21980453323234211, 0.23636363701386887]

In [185]:
print("Linear Regression - Mean Absolute Error ", "train:",lr[0], "test:",lr[1])
print("Ridge Regression - Mean Absolute Error ", "train:",lr[0], "test:",lr[1])
print("Logistic Model - Accuracy:", lm[1])
print("Decision Tree - Accuracy:", dt[1])
print("Random Forest - Accuracy:", rf[1])
print("Naive Bayes - Accuracy:", nb[1])
print("Neural Net - Mean Absolute Error:", l_and_m[1], " Categorial Accuracy:", l_and_m[2])

Linear Regression - Mean Absolute Error  train: 71885.5362553 test: 74125.2913808
Ridge Regression - Mean Absolute Error  train: 71885.5362553 test: 74125.2913808
Logistic Model - Accuracy: 0.490909090909
Decision Tree - Accuracy: 0.909090909091
Random Forest - Accuracy: 0.967272727273
Naive Bayes - Accuracy: 0.487272727273
Neural Net - Mean Absolute Error: 0.219804533232  Categorial Accuracy: 0.236363637014