In [1]:
# import_notebooks is a custom python script
# this line makes it possible to import functions from other IPython notebooks
from import_notebooks import *

In [2]:
# Here we import all the functions (*) from these notebooks
from Hainan_Data_Cleaning import *
from time_shift_dataframe import *
from Stratified_Split import *
from Cumulative import *
from Rollingsum import *
from LR_model import *
from Classification_Functions import *
from nn_model_keras import *

from Utilities import *

importing Jupyter notebook from Hainan_Data_Cleaning.ipynb
importing Jupyter notebook from time_shift_dataframe.ipynb
importing Jupyter notebook from Stratified_Split.ipynb
importing Jupyter notebook from Cumulative.ipynb
importing Jupyter notebook from Rollingsum.ipynb
importing Jupyter notebook from LR_model.ipynb

C:\Users\Ashis\Anaconda3\envs\data-x\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

importing Jupyter notebook from Classification_Functions.ipynb
importing Jupyter notebook from nn_model_keras.ipynb

Using TensorFlow backend.

importing Jupyter notebook from Utilities.ipynb

In [3]:
# load_hainan_data() is from Hainan_Data_Cleaning and it loads hainan data
df = load_hainan_data()
df_ts = timeshift_df(df, 15)

df_ts.columns.values
df_ts_relfeatures = df_ts.drop(['Year', 'Month', 'Day','BioCNG', 'LiquidFertilizer',
       'SolidFertilizer', 'WasteWater', 'SolidResidues','ProjectElectricity',
       'OfficeElectricity', 'Water', 'Diesel'], axis=1)

print(df_ts_relfeatures.shape[0])
df_ts_relfeatures = df_ts_relfeatures.apply(pd.to_numeric, errors='coerce')
df_ts_relfeatures = df_ts_relfeatures.dropna()
print(df_ts_relfeatures.shape[0])

df_ts_relfeatures_roll = rollingsum(df_ts_relfeatures,10)

1413
1413

In [4]:
df = df_ts_relfeatures
df.head()

,RawBiogas,PigManure,Cassava,FishWastewater,KitchenFoodWaste,MunicipalFecalWaste,TeaWaste,ChickenWaste,Bagasse,AlcoholWaste,ChineseMedicineWaste,EnergyGrass,BananaFruitShafts,LemonWaste,Percolate,Other,NaOH,FeCl2,PAM,Defoamer
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,14.9,0.0,0.0,0.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
df_final = df_ts_relfeatures_roll
print(df_final.shape)
df_final.head()

(1403, 20)

,RawBiogas,PigManure,Cassava,FishWastewater,KitchenFoodWaste,MunicipalFecalWaste,TeaWaste,ChickenWaste,Bagasse,AlcoholWaste,ChineseMedicineWaste,EnergyGrass,BananaFruitShafts,LemonWaste,Percolate,Other,NaOH,FeCl2,PAM,Defoamer
0,27415.0,86.20,0.0,0.0,0.0,0.0,0.0,0.0,75.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,35331.0,103.24,0.0,0.0,0.0,0.0,0.0,0.0,90.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,41077.0,103.24,0.0,0.0,0.0,0.0,0.0,0.0,90.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,46603.0,103.24,0.0,0.0,0.0,0.0,0.0,0.0,90.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,53365.0,88.34,0.0,0.0,0.0,0.0,0.0,0.0,77.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
x_train_r, y_train_r, x_test_r, y_test_r = test_train_for_regression(df_final)
x_train_c, y_train_c, x_test_c, y_test_c = test_train_for_classification(df_final, num_buckets = 7)
x_train_c_1, y_train_c_1, x_test_c_1, y_test_c_1 = test_train_for_classification(df_final, \
                                output_var="RawBiogas", \
                                num_buckets = 7, one_hot=True)

print(x_train_r.shape,  y_train_r.shape, x_test_r.shape, y_test_r.shape)
# print(x_train_r.columns.values)

(1122, 19) (1122,) (281, 19) (281,)

In [7]:
# Linear Regression
lr = run_lm(x_train_r, y_train_r, x_test_r, y_test_r)

Starting linear regression model.
                            OLS Regression Results
==============================================================================
Dep. Variable:              RawBiogas   R-squared:                       0.751
Model:                            OLS   Adj. R-squared:                  0.747
Method:                 Least Squares   F-statistic:                     175.3
Date:                Mon, 16 Apr 2018   Prob (F-statistic):          1.44e-316
Time:                        03:44:56   Log-Likelihood:                -13121.
No. Observations:                1122   AIC:                         2.628e+04
Df Residuals:                    1102   BIC:                         2.638e+04
Df Model:                          19
Covariance Type:            nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
const                  4.94e+04   1982.578     24.919      0.000    4.55e+04    5.33e+04
PigManure               -2.0811      1.574     -1.322      0.186      -5.170       1.008
Cassava                 68.1406      4.291     15.879      0.000      59.721      76.560
FishWastewater          -7.5691     32.936     -0.230      0.818     -72.194      57.056
KitchenFoodWaste       161.9635     27.293      5.934      0.000     108.412     215.515
MunicipalFecalWaste     15.1359      6.081      2.489      0.013       3.204      27.067
TeaWaste                26.3463     57.532      0.458      0.647     -86.538     139.230
ChickenWaste           -72.1220     45.770     -1.576      0.115    -161.928      17.684
Bagasse                 62.3657      8.787      7.098      0.000      45.125      79.607
AlcoholWaste            12.7324     50.186      0.254      0.800     -85.739     111.204
ChineseMedicineWaste   743.6353    163.355      4.552      0.000     423.113    1064.157
EnergyGrass              3.1216    197.881      0.016      0.987    -385.145     391.388
BananaFruitShafts      298.2184     59.474      5.014      0.000     181.523     414.914
LemonWaste            -290.2291    174.319     -1.665      0.096    -632.263      51.805
Percolate                5.6683      1.684      3.367      0.001       2.365       8.972
Other                  -28.1178     14.158     -1.986      0.047     -55.898      -0.338
NaOH                    -1.0216      0.323     -3.163      0.002      -1.655      -0.388
FeCl2                   -6.2522      2.016     -3.102      0.002     -10.208      -2.297
PAM                    182.3381     29.688      6.142      0.000     124.087     240.589
Defoamer              -434.0419   1142.316     -0.380      0.704   -2675.403    1807.319
==============================================================================
Omnibus:                       32.818   Durbin-Watson:                   1.973
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               49.905
Skew:                           0.268   Prob(JB):                     1.46e-11
Kurtosis:                       3.883   Cond. No.                     7.76e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 7.76e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
The mean absolute error of linear regression on training set is:  21597.5568336
The mean absolute error of linear regression test set is:  19971.1074232

In [8]:
rr = run_ridge(x_train_r, y_train_r, x_test_r, y_test_r, alpha = 0.5)

# Classification
lm = LogisticModel(x_train_c, y_train_c, x_test_c, y_test_c)

dt = DecisionTree(x_train_c, y_train_c, x_test_c, y_test_c)

rf = RandomForest(x_train_c, y_train_c, x_test_c, y_test_c)

nb = NaiveBayes(x_train_c, y_train_c, x_test_c, y_test_c)


# Neural Net 
l_and_m = run_keras_nn(x_train_c_1, y_train_c_1, x_test_c_1, y_test_c_1, \
             epochs=10, hidden_layers=6, layer_neurons = 300, \
             activation='tanh', learning_rate=0.01)

The mean absolute error of ridge regression on training set is:  24032.437563
The mean absolute error of ridge regression test set is:  23182.92333
Starting keras model.
19
7
Epoch 1/10
1122/1122 [==============================] - 1s 1ms/step - loss: 1.4233 - mean_absolute_error: 0.1933 - categorical_accuracy: 0.4340
Epoch 2/10
1122/1122 [==============================] - 0s 309us/step - loss: 1.2950 - mean_absolute_error: 0.1803 - categorical_accuracy: 0.4804
Epoch 3/10
1122/1122 [==============================] - 0s 357us/step - loss: 1.2837 - mean_absolute_error: 0.1763 - categorical_accuracy: 0.4768
Epoch 4/10
1122/1122 [==============================] - 0s 339us/step - loss: 1.3154 - mean_absolute_error: 0.1824 - categorical_accuracy: 0.4670
Epoch 5/10
1122/1122 [==============================] - 0s 308us/step - loss: 1.2754 - mean_absolute_error: 0.1785 - categorical_accuracy: 0.4804
Epoch 6/10
1122/1122 [==============================] - 0s 331us/step - loss: 1.2567 - mean_absolute_error: 0.1774 - categorical_accuracy: 0.4875
Epoch 7/10
1122/1122 [==============================] - 0s 322us/step - loss: 1.2299 - mean_absolute_error: 0.1776 - categorical_accuracy: 0.5009
Epoch 8/10
1122/1122 [==============================] - 0s 323us/step - loss: 1.2574 - mean_absolute_error: 0.1748 - categorical_accuracy: 0.4866
Epoch 9/10
1122/1122 [==============================] - 0s 338us/step - loss: 1.1968 - mean_absolute_error: 0.1724 - categorical_accuracy: 0.5089
Epoch 10/10
1122/1122 [==============================] - 0s 329us/step - loss: 1.2140 - mean_absolute_error: 0.1729 - categorical_accuracy: 0.5027
281/281 [==============================] - 0s 216us/step
[1.6771625369469041, 0.18947851413933833, 0.423487543529463]

In [10]:
print("Linear Regression - Mean Absolute Error ", "train:",lr[0], "test:",lr[1])
print("Ridge Regression - Mean Absolute Error ", "train:",lr[0], "test:",lr[1])
print("Logistic Model - Accuracy:", lm[1])
print("Decision Tree - Accuracy:", dt[1])
print("Random Forest - Accuracy:", rf[1])
print("Naive Bayes - Accuracy:", nb[1])
print("Neural Net - Mean Absolute Error:", l_and_m[1], " Categorial Accuracy:", l_and_m[2])

Linear Regression - Mean Absolute Error  train: 21597.5568336 test: 19971.1074232
Ridge Regression - Mean Absolute Error  train: 21597.5568336 test: 19971.1074232
Logistic Model - Accuracy: 0.580071174377
Decision Tree - Accuracy: 0.715302491103
Random Forest - Accuracy: 0.811387900356
Naive Bayes - Accuracy: 0.362989323843
Neural Net - Mean Absolute Error: 0.189478514139  Categorial Accuracy: 0.423487543529